module CiaoApp {
   interface CiaoCallback {
      void callback(in string message);
   };
   interface Ciao {
      string say(in string id, in string message);
	  void register(in CiaoCallback callobj);
	 
	  
   };
   
   
};