package CiaoApp;


/**
* CiaoApp/CiaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 17:53:42 o'clock IST
*/

public interface CiaoOperations 
{
  String say (CiaoApp.CiaoCallback objref, String id, String message);
} // interface CiaoOperations
