package CiaoApp;


/**
* CiaoApp/Ciao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 17:53:42 o'clock IST
*/

public interface Ciao extends CiaoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ciao
