package CiaoApp;


/**
* CiaoApp/CiaoCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 17:53:42 o'clock IST
*/

public interface CiaoCallbackOperations 
{
  void callback (String message);
} // interface CiaoCallbackOperations
