package CiaoApp;


/**
* CiaoApp/CiaoCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Friday, July 11, 2014 12:52:14 PM IST
*/

public interface CiaoCallbackOperations 
{
  void callback (String message);
} // interface CiaoCallbackOperations
