package CiaoApp;


/**
* CiaoApp/CiaoCallbackHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 22:54:56 o'clock IST
*/

abstract public class CiaoCallbackHelper
{
  private static String  _id = "IDL:CiaoApp/CiaoCallback:1.0";

  public static void insert (org.omg.CORBA.Any a, CiaoApp.CiaoCallback that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CiaoApp.CiaoCallback extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CiaoApp.CiaoCallbackHelper.id (), "CiaoCallback");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CiaoApp.CiaoCallback read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CiaoCallbackStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CiaoApp.CiaoCallback value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CiaoApp.CiaoCallback narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CiaoApp.CiaoCallback)
      return (CiaoApp.CiaoCallback)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CiaoApp._CiaoCallbackStub stub = new CiaoApp._CiaoCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CiaoApp.CiaoCallback unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CiaoApp.CiaoCallback)
      return (CiaoApp.CiaoCallback)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CiaoApp._CiaoCallbackStub stub = new CiaoApp._CiaoCallbackStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
