package CiaoApp;

/**
* CiaoApp/CiaoCallbackHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 14:30:09 o'clock IST
*/

public final class CiaoCallbackHolder implements org.omg.CORBA.portable.Streamable
{
  public CiaoApp.CiaoCallback value = null;

  public CiaoCallbackHolder ()
  {
  }

  public CiaoCallbackHolder (CiaoApp.CiaoCallback initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CiaoApp.CiaoCallbackHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CiaoApp.CiaoCallbackHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CiaoApp.CiaoCallbackHelper.type ();
  }

}
