package CiaoApp;


/**
* CiaoApp/CiaoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Friday, July 11, 2014 12:52:14 PM IST
*/

abstract public class CiaoHelper
{
  private static String  _id = "IDL:CiaoApp/Ciao:1.0";

  public static void insert (org.omg.CORBA.Any a, CiaoApp.Ciao that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CiaoApp.Ciao extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CiaoApp.CiaoHelper.id (), "Ciao");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CiaoApp.Ciao read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CiaoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CiaoApp.Ciao value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CiaoApp.Ciao narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CiaoApp.Ciao)
      return (CiaoApp.Ciao)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CiaoApp._CiaoStub stub = new CiaoApp._CiaoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CiaoApp.Ciao unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CiaoApp.Ciao)
      return (CiaoApp.Ciao)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CiaoApp._CiaoStub stub = new CiaoApp._CiaoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
