package CiaoApp;


/**
* CiaoApp/CiaoCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 14:17:45 o'clock IST
*/

public interface CiaoCallback extends CiaoCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CiaoCallback
