package CiaoApp;


/**
* CiaoApp/CiaoCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Friday, July 11, 2014 12:52:14 PM IST
*/

public interface CiaoCallback extends CiaoCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CiaoCallback
