package CiaoApp;


/**
* CiaoApp/CiaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Friday, July 11, 2014 12:52:14 PM IST
*/

public interface CiaoOperations 
{
  String say (CiaoApp.CiaoCallback objref, String message);
} // interface CiaoOperations
