package CiaoApp;


/**
* CiaoApp/CiaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ciao.idl
* Monday, 11 August 2014 22:54:56 o'clock IST
*/

public interface CiaoOperations 
{
  String say (String id, String message);
  void register (CiaoApp.CiaoCallback callobj);
} // interface CiaoOperations
